### ISSUE TITLE
Source RNG?

### ISSUE THREAD

**Issue by TomMD** [prowdsponsor/crypto-conduit#1]
Is there a reason not to have a source for random numbers?  Something like:

```
sourceRNG :: (ResourceIO m, CryptoRandomGen g) => Seed -> Bytes-> Proxy g -> Source m ByteString
```

Allowing code to be something like the below if you like tagging.  If you don't like tagging I'm not sure how to make a phantom type get carried implicitly inside Source - perhaps by making the result a tuple of (g,ByteString)?  that would be ugly though.

```
rngSource :: (ResourceIO m, CryptoRandomGen g) => Tagged g (Source m ByteString)
rngSource = do
  let p = Proxy
       entLen   = genSeedLength `proxy` p
  ent <- getEntropy entLen
  sourceRNG ent 128 p
```

**Comment by meteficha** [comment]
I was going to write something like that but I've refrained from doing so on this first `crypto-conduit` version.  

The biggest reason is that I don't really know what to do about reseeding.  I could just ignore it like you did on your example signature, but I didn't like the idea of saying "hey, they have that on `crypto-api` but you don't need it!".  (Of course, given a function with reseeding support, we could provide a simplified one that doesn't do any reseeding.)  

Another reason is that I didn't find at the time a nice use case that would justify the head-scratching on the issue above.

Thoughts?

**Comment by TomMD** [comment]
On Wed, Jan 11, 2012 at 10:21 AM, Felipe Lessa
reply@reply.github.com
wrote:

> I was going to write something like that but I've refrained from doing so on this first `crypto-conduit` version.
> 
> The biggest reason is that I don't really know what to do about reseeding.  I could just ignore it like you did on your example signature, but I didn't like the idea of saying "hey, they have that on `crypto-api` but you don't need it!".  (Of course, given a function with reseeding support, we could provide a simplified one that doesn't do any reseeding.)
> 
> Another reason is that I didn't find at the time a nice use case that would justify the head-scratching on the issue above.
> 
> Thoughts?

Those are both fair reasons.  Until more people start using RNG
properly, including catching and reseeding at the right times, perhaps
this is premature.  One thing that could be done is an appropriate
buffered and auto-reseeding generator (AES or hash based) with
SystemRandom a la the DRBG code:

```
GenBuffered (GenAutoReseed AESCtrGen SystemRandom)
```

Thus forcing sourceRNG to be of type

```
:: BlockSize -> Source IO ByteString
```

But that many decisions forced on the user might be too overbearing.
I'm just not sure how flexible the source needs to be to make enough
users happy.

**Comment by meteficha** [comment]
Then let's wait for someone with a real use case in hands before we make any decisions.  I'd like to support as much of `crypto-api` as possible, but this problem is too under-specified =).
