### ISSUE TITLE
Crypto-api changes will (probably) break crypto-conduit

### ISSUE THREAD

**Issue by TomMD** [prowdsponsor/crypto-conduit#17]
The changes I have lined up, which are not final, will likely break conduit due to the moving of modes from one module to another.  This is a place holder for me (or you, at your option) to test and ensure things work out.

**Comment by meteficha** [comment]
@TomMD Now that you mention it: what's `crypto-api` role right now?  It seems I can't even use anything from `cryptocipher` anymore with it.  Are the changes you're lining up going to make it usable again?

**Comment by TomMD** [comment]
The issue with cryptocipher is that the instances for Crypto-API have mostly been dropped.  Near as I understand, Vincent did this due to a combination of performance concerns and desire to minimize dependencies when refactoring.  One change I am making is adding cipher modes to the BlockCipher class, thus allowing higher performance C/ASM routines to be used for the modes such as CBC and CTR.  I should also probably send a patch Vincent's way that adds instances for cipher-aes inside the cryptocipher framework (which already depends on Crypto-API).

**Comment by meteficha** [comment]
Great, that's nice to hear!
