### ISSUE TITLE
Add conduitHmac

### ISSUE THREAD

**Issue by drchaos** [prowdsponsor/crypto-conduit#22]
Library contains sink sinkHmac. However, I need almost the same conduit that transmits input to output and saves the digest to IORef.
The simplest way is to copy and paste sinkHmac ,
add yield bs before go ctx'
replace return outer with liftIO$ writeIORef ref outer >> return () .
But maybe exists more elegant way?

**Comment by snoyberg** [comment]
I just pushed a commit to conduit which adds a new function called `passthroughSink` with the following type signature:

``` haskell
passthroughSink :: Monad m
                => Sink i m r
                -> (r -> m ()) -- ^ finalizer
                -> Conduit i m i
```

I think this will allow you to achieve the use case you're looking for without adding an extra function to `crypto-conduit`. Can you check it out and see if it fits your needs?

**Comment by drchaos** [comment]
Big thanks! Seems like it should fit. I will check.

**Comment by drchaos** [comment]
It works! Thank a lot.
